# Generated by Django 3.1.3 on 2021-07-02 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('login', models.CharField(default='anonymus', max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_urodzenia', models.DateField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('has_perms', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gracze',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turnieje',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=20)),
                ('ilosc_graczy', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12'), (14, '14'), (16, '16'), (18, '18'), (20, '20'), (22, '22'), (24, '24')])),
                ('data_rozpoczecia', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mecze',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('faza', models.IntegerField()),
                ('wynik_gracza1', models.IntegerField(blank=True, null=True)),
                ('wynik_gracza2', models.IntegerField(blank=True, null=True)),
                ('id_gracza1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gracz1', to='app_turnieje.gracze')),
                ('id_gracza2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gracz2', to='app_turnieje.gracze')),
                ('id_turnieju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turnieje.turnieje')),
                ('wygrana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zwyciezca', to='app_turnieje.gracze')),
            ],
        ),
        migrations.AddField(
            model_name='gracze',
            name='id_turnieju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turnieje.turnieje'),
        ),
    ]
