# Generated by Django 3.1.3 on 2021-06-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=20)),
                ('haslo', models.CharField(max_length=1024)),
                ('mail', models.CharField(max_length=100)),
                ('data_urodzenia', models.DateTimeField()),
            ],
        ),
    ]
