# Generated by Django 3.1.3 on 2021-06-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnieje',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=20)),
                ('ilosc_graczy', models.IntegerField()),
                ('data_rozpoczecia', models.DateTimeField()),
                ('godzina_rozpoczecia', models.TimeField()),
            ],
        ),
    ]
