# Generated by Django 3.1.3 on 2021-07-02 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnieje',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
