# Generated by Django 3.1.3 on 2021-07-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='has_module_perms',
        ),
    ]
