# Generated by Django 3.1.3 on 2021-07-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gracze',
            old_name='imie',
            new_name='imie_nazwisko',
        ),
        migrations.RemoveField(
            model_name='gracze',
            name='nazwisko',
        ),
    ]
