# Generated by Django 3.1.3 on 2021-06-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0002_turnieje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnieje',
            name='godzina_rozpoczecia',
        ),
    ]
