# Generated by Django 3.1.3 on 2021-07-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0002_auto_20210704_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraczeWTurnieju',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('gracz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turnieje.gracze')),
                ('turniej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turnieje.turnieje')),
            ],
        ),
    ]
