# Generated by Django 3.1.3 on 2021-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0002_auto_20210702_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnieje',
            name='autor',
            field=models.CharField(default='Anonymus', max_length=50),
        ),
    ]
