# Generated by Django 3.1.3 on 2021-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0003_auto_20210702_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownicy',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
