# Generated by Django 3.1.3 on 2021-06-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0003_remove_turnieje_godzina_rozpoczecia'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnieje',
            name='autor',
            field=models.CharField(default='Anonymus', max_length=20),
        ),
    ]
