# Generated by Django 3.1.3 on 2021-07-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0004_auto_20210702_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gracze',
            name='id_turnieju',
        ),
    ]
