# Generated by Django 3.1.3 on 2021-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0005_auto_20210623_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnieje',
            name='autor',
            field=models.CharField(default='Anonymus', max_length=20),
        ),
    ]
