# Generated by Django 3.1.3 on 2021-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0006_auto_20210623_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gracze',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('id_turnieju', models.IntegerField()),
            ],
        ),
    ]
