# Generated by Django 3.1.3 on 2021-06-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0008_auto_20210624_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gracze',
            name='id_turnieju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turnieje.turnieje'),
        ),
    ]
