# Generated by Django 3.1.3 on 2021-06-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0012_auto_20210624_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnieje',
            name='ilosc_graczy',
            field=models.IntegerField(choices=[(1, '2'), (2, '4'), (3, '6'), (4, '8'), (5, '10'), (6, '12'), (7, '14'), (8, '16'), (9, '18'), (10, '20'), (11, '22'), (12, '24')]),
        ),
        migrations.CreateModel(
            name='Mecze',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('faza', models.IntegerField()),
                ('wynik_gracza1', models.IntegerField()),
                ('wynik_gracza2', models.IntegerField()),
                ('id_gracza1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gracz1', to='app_turnieje.gracze')),
                ('id_gracza2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gracz2', to='app_turnieje.gracze')),
                ('id_turnieju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turnieje.turnieje')),
                ('wygrana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zwyciezca', to='app_turnieje.gracze')),
            ],
        ),
    ]
