# Generated by Django 3.1.3 on 2021-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0013_auto_20210629_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecze',
            name='wynik_gracza1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mecze',
            name='wynik_gracza2',
            field=models.IntegerField(blank=True),
        ),
    ]
