# Generated by Django 3.1.3 on 2021-06-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0015_auto_20210629_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecze',
            name='wygrana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zwyciezca', to='app_turnieje.gracze'),
        ),
        migrations.AlterField(
            model_name='mecze',
            name='wynik_gracza1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mecze',
            name='wynik_gracza2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
