# Generated by Django 3.1.3 on 2021-07-01 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0016_auto_20210629_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='haslo',
        ),
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='nazwa',
        ),
        migrations.AddField(
            model_name='uzytkownicy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uzytkownicy',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uzytkownicy',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='uzytkownicy',
            name='login',
            field=models.CharField(default='anonymus', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='uzytkownicy',
            name='password',
            field=models.CharField(default=1234, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnieje',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='data_urodzenia',
            field=models.DateField(),
        ),
    ]
