# Generated by Django 3.1.3 on 2021-07-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0018_uzytkownicy_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='is_superuser',
        ),
    ]
