# Generated by Django 3.1.3 on 2021-07-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0025_remove_uzytkownicy_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownicy',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
