# Generated by Django 3.1.3 on 2021-07-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0027_uzytkownicy_has_module_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownicy',
            name='has_perm',
            field=models.BooleanField(default=False),
        ),
    ]
