# Generated by Django 3.1.3 on 2021-07-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0028_uzytkownicy_has_perm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownicy',
            old_name='has_perm',
            new_name='has_perms',
        ),
    ]
