# Generated by Django 3.1.3 on 2021-07-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnieje', '0029_auto_20210701_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnieje',
            name='autor',
            field=models.CharField(default='Anonymus', max_length=50),
        ),
    ]
